// The campaigns family: a refactor tracked as an object in the repository —
// `objectives`, each a detector with a ledger that only shrinks on its own,
// over `sectors` the code declares through a `perimeter`, through ordered
// `phases` toward an end.
//
// It is a family @goodbones/core does not own. A host composes it:
//
//   loadPolicy({ …, extensions: [campaignsExtension({ functions, reports })] })
//
// and reads its state back with `campaignsOf(policy)`. The core carries the
// value and never looks inside it, which is what keeps a policy that only
// states architecture from paying for any of this.
export {
  type CampaignEvaluation,
  type CampaignEvaluationInput,
  evaluateCampaign,
  hitsInWindow,
  type ObjectiveHit,
  type SectorState,
  towardNextOf,
} from "./core/campaign-state.js";
export {
  type CampaignHit,
  type CampaignInput,
  campaignsFailingTheirProbe,
  campaignsSelecting,
  compileCampaignRule,
  compileCampaignRules,
  type CompiledCampaign,
  type CompiledDetector,
  type CompiledMeasure,
  type CompiledMeasureSource,
  type CompiledObjective,
  type CompiledPerimeter,
  type CompiledSectorTerm,
  compileObjective,
  candidatesOf as detectorCandidatesOf,
  detectorOf,
  distanceToTarget,
  evaluateObjective,
  evaluateObjectives,
  explainDetector,
  explainObjective,
  type FailedProbe,
  leafTermsOf,
  matchKeyOf,
  measureDetectorsOf,
  measureFile,
  type MeasureParts,
  needsSyntax,
  numberFromOutput,
  perFileMeasuresOf,
  perFileObjectivesOf,
  probeInputOf,
  reportSpecsOf,
  roundMeasure,
  type TermAnswer,
  valueOfParts,
} from "./core/campaigns.js";
export {
  allowedOf,
  type Attestation,
  attestedRecord,
  clearedMeasure,
  clearedOf,
  clearedSector,
  closedOf,
  concededMeasure,
  concededSector,
  type Concession,
  type ConcessionRecord,
  decodeLedger,
  decodeMeasureLedger,
  decodePlanRecord,
  decodeSectorRecord,
  deltaOf,
  EMPTY_LEDGER,
  EMPTY_MEASURE_LEDGER,
  EMPTY_SECTOR_RECORD,
  encodeSectorName,
  holdoutsOf,
  initialOf,
  isComplete,
  isLegacyLedger,
  isMeasureLedger,
  isStalled,
  lastClearedOf,
  lastImprovedOf,
  type Ledger,
  ledgerArithmeticHolds,
  ledgerPathOf,
  Ledger as LedgerSchema,
  legacyLedgerPathOf,
  measureArithmeticHolds,
  type MeasureConcession,
  type MeasureLedger,
  measureLedgerArithmeticHolds,
  MeasureLedger as MeasureLedgerSchema,
  measureProgressOf,
  type MeasureSectorLedger,
  measureStandingOf,
  type Note,
  NOTE_CAP,
  NOTE_LENGTH,
  notedRecord,
  type PlanDiff,
  planDiffOf,
  planOf,
  planPathOf,
  type PlanRecord,
  positionOf,
  progressOf,
  reachedRecord,
  rebaselinedSector,
  reconcileSector,
  type Reconciliation,
  recordedOf,
  sectorArithmeticHolds,
  sectorClockOf,
  type SectorLedger,
  type SectorRecord,
  sectorRecordPathOf,
  serializeLedger,
  serializeMeasureLedger,
  serializePlanRecord,
  serializeSectorRecord,
} from "./core/ledger.js";
export {
  compareResidue,
  derivePhase,
  type Direction,
  directionOf,
  donePhaseOf,
  growsAt,
  inWindow,
  isDefinedPhase,
  isOpenPhase,
  isShut,
  ledgeredFor,
  LEGACY_PHASE,
  objectivesInWindow,
  onTouchOf,
  type Residue as ResidueVector,
  type SectorPosition,
  sharedWindow,
  UNPLACED,
  type Window,
  windowOf,
  worsened,
} from "./core/phases.js";
export {
  discoverSectors,
  fixedPrefixOf,
  IMPLICIT_SECTOR,
  isShared,
  LEGACY_SECTOR,
  membershipOf,
  parseSectorMarker,
  type Placement,
  rootOf,
  type Sector,
  SECTOR_HOLDOUT,
  type SectorDiscovery,
  entryOf as sectorEntryOf,
  type SectorIndex,
  type SectorMarker,
  sectorNamed,
  SHARED_SECTOR,
  withoutExtension,
} from "./core/sectors.js";
export {
  type CampaignProbe,
  type CampaignProbes,
  type CampaignRule,
  type CampaignUnit,
  type Detector,
  type Holdout,
  type Measure,
  type MeasureDirection,
  type MeasureSource,
  type ObjectiveRule,
  type OnTouch,
  type PerimeterRule,
  type PhaseConcession,
  type PhaseRule,
  type ProbeDiagnostic,
  type SectorTerm,
} from "./domain/config.js";
export {
  type Diagnostic,
  indexByFile,
  parseReport,
  type ParseReportOptions,
  type ReportFormat,
  uniqueDiagnostics,
} from "./domain/report.js";
export {
  attest,
  authorOf,
  concede,
  type ConcedeOutcome,
  evaluateCampaigns,
  historyOf,
  type HistoryRow,
  note,
  type Readers,
  renderHistory,
  widenedExtensions,
} from "./host/campaigns.js";
export { clear, type ClearOutcome, type SectorMove, sectorMovesOf } from "./host/clear.js";
export {
  type Commit,
  commitOf,
  commitsTouching,
  type Diff,
  distanceToHunks,
  type Hunk,
  materializeTree,
  parseDiff,
  readDiff,
  textAt,
} from "./host/diff.js";
export { explainCampaignLines } from "./host/explain.js";
export { growsFor, ledgerPhaseOf } from "./host/ledger-phase.js";
export { HOLDOUT_CAP } from "./host/ledgers.js";
export {
  type Ask,
  type BaseSide,
  baseSideAt,
  baseSideOf,
  type Nudge,
  type NudgeHoldout,
  nudgeOf,
  renderNudge,
  type SectorNudge,
  type Verdict,
} from "./host/nudge.js";
export {
  campaignFailuresOf,
  type CampaignReport,
  campaignReportsOf,
  ledgeredFilter,
  type ObjectiveReport,
  renderCampaignReports,
  type SectorObjectiveReport,
  type SectorReport,
} from "./host/report.js";
export { renderCampaignRows, snapshotCampaignsOf } from "./host/status.js";
export {
  loadCampaignFunctions,
  type LoadedCampaignFunctions,
} from "./infrastructure/campaign-functions.js";
export { makeReportSourceLive } from "./infrastructure/report-source-live.js";
export {
  type CampaignPolicy,
  CAMPAIGNS_EXTENSION_ID,
  campaignsExtension,
  type CampaignsExtensionOptions,
  campaignsOf,
  ledgerKeyOf,
} from "./load/extension.js";
export {
  END_STATE_ROOT,
  endStateObjectiveId,
  lowerCampaigns,
  lowerEndState,
} from "./manifest/lower.js";
export {
  type CampaignProbeSpec,
  type CampaignProbesSpec,
  CampaignsManifest,
  type CampaignSpec,
  DEFAULT_LEDGER_DIR,
  type DetectorSpec,
  durationMs,
  type EndStateSpec,
  type MeasureSourceSpec,
  type ObjectiveSpec,
  type PerimeterSpec,
  type PhaseSpec,
  type SectorTermSpec,
  type SyntaxTermSpec,
} from "./manifest/spec.js";
export { type CampaignMeasure } from "./ports/campaign-measure.js";
export {
  type CampaignPredicate,
  type CampaignPredicateInput,
  type CampaignSubject,
  type Range,
} from "./ports/campaign-predicate.js";
export {
  NO_REPORTS,
  type ReportSource,
  reportSourcesOf,
  type ReportSpec,
} from "./ports/report-source.js";
