// The campaigns family: a refactor tracked as an object in the repository —
// `objectives`, each a detector with a ledger that only shrinks on its own,
// over `sectors` the code declares through a `perimeter`, through ordered
// `phases` toward an end.
//
// It is a family @goodbones/core does not own. A host composes it:
//
//   loadPolicy({ …, extensions: [campaignsExtension({ functions, reports })] })
//
// and reads its state back with `campaignsOf(policy)`. The core carries the
// value and never looks inside it, which is what keeps a policy that only
// states architecture from paying for any of this.
export {
  type CampaignEvaluation,
  type CampaignEvaluationInput,
  evaluateCampaign,
  hitsInWindow,
  type ObjectiveHit,
  type SectorState,
  towardNextOf,
} from "./core/campaign-state.js";
export {
  type CampaignHit,
  type CampaignInput,
  campaignsFailingTheirProbe,
  campaignsSelecting,
  compileCampaignRule,
  compileCampaignRules,
  type CompiledCampaign,
  type CompiledDetector,
  type CompiledObjective,
  type CompiledPerimeter,
  type CompiledSectorTerm,
  compileObjective,
  candidatesOf as detectorCandidatesOf,
  detectorOf,
  evaluateObjective,
  evaluateObjectives,
  explainDetector,
  explainObjective,
  type FailedProbe,
  leafTermsOf,
  matchKeyOf,
  needsSyntax,
  perFileObjectivesOf,
  probeInputOf,
  reportSpecsOf,
  type TermAnswer,
} from "./core/campaigns.js";
export {
  allowedOf,
  type Attestation,
  attestedRecord,
  clearedOf,
  clearedSector,
  closedOf,
  concededSector,
  type Concession,
  type ConcessionRecord,
  decodeLedger,
  decodePlanRecord,
  decodeSectorRecord,
  deltaOf,
  EMPTY_LEDGER,
  EMPTY_SECTOR_RECORD,
  encodeSectorName,
  holdoutsOf,
  initialOf,
  isComplete,
  isLegacyLedger,
  isStalled,
  lastClearedOf,
  type Ledger,
  ledgerArithmeticHolds,
  ledgerPathOf,
  Ledger as LedgerSchema,
  legacyLedgerPathOf,
  type Note,
  NOTE_CAP,
  NOTE_LENGTH,
  notedRecord,
  type PlanDiff,
  planDiffOf,
  planOf,
  planPathOf,
  type PlanRecord,
  positionOf,
  progressOf,
  reachedRecord,
  rebaselinedSector,
  reconcileSector,
  type Reconciliation,
  sectorArithmeticHolds,
  sectorClockOf,
  type SectorLedger,
  type SectorRecord,
  sectorRecordPathOf,
  serializeLedger,
  serializePlanRecord,
  serializeSectorRecord,
} from "./core/ledger.js";
export {
  compareResidue,
  derivePhase,
  type Direction,
  donePhaseOf,
  inWindow,
  isDefinedPhase,
  isOpenPhase,
  isShut,
  LEGACY_PHASE,
  objectivesInWindow,
  onTouchOf,
  type Residue as ResidueVector,
  type SectorPosition,
  UNPLACED,
  type Window,
  windowOf,
  worsened,
} from "./core/phases.js";
export {
  discoverSectors,
  fixedPrefixOf,
  IMPLICIT_SECTOR,
  LEGACY_SECTOR,
  membershipOf,
  parseSectorMarker,
  type Placement,
  rootOf,
  type Sector,
  SECTOR_HOLDOUT,
  type SectorDiscovery,
  entryOf as sectorEntryOf,
  type SectorIndex,
  type SectorMarker,
  sectorNamed,
  withoutExtension,
} from "./core/sectors.js";
export {
  type CampaignProbe,
  type CampaignProbes,
  type CampaignRule,
  type CampaignUnit,
  type Detector,
  type Holdout,
  type ObjectiveRule,
  type OnTouch,
  type PerimeterRule,
  type PhaseConcession,
  type PhaseRule,
  type ProbeDiagnostic,
  type SectorTerm,
} from "./domain/config.js";
export {
  type Diagnostic,
  indexByFile,
  parseReport,
  type ParseReportOptions,
  type ReportFormat,
  uniqueDiagnostics,
} from "./domain/report.js";
export {
  type Ask,
  attest,
  authorOf,
  type BaseSide,
  baseSideAt,
  baseSideOf,
  campaignFailuresOf,
  type CampaignReport,
  campaignReportsOf,
  clear,
  type ClearOutcome,
  concede,
  type ConcedeOutcome,
  evaluateCampaigns,
  explainCampaignLines,
  historyOf,
  type HistoryRow,
  HOLDOUT_CAP,
  ledgeredFilter,
  note,
  type Nudge,
  type NudgeHoldout,
  nudgeOf,
  type ObjectiveReport,
  type Readers,
  renderCampaignReports,
  renderCampaignRows,
  renderHistory,
  renderNudge,
  type SectorNudge,
  type SectorObjectiveReport,
  type SectorReport,
  snapshotCampaignsOf,
  type Verdict,
  widenedExtensions,
} from "./host/campaigns.js";
export {
  type Commit,
  commitOf,
  commitsTouching,
  type Diff,
  distanceToHunks,
  type Hunk,
  materializeTree,
  parseDiff,
  readDiff,
  textAt,
} from "./host/diff.js";
export {
  loadCampaignFunctions,
  type LoadedCampaignFunctions,
} from "./infrastructure/campaign-functions.js";
export { makeReportSourceLive } from "./infrastructure/report-source-live.js";
export {
  type CampaignPolicy,
  CAMPAIGNS_EXTENSION_ID,
  campaignsExtension,
  type CampaignsExtensionOptions,
  campaignsOf,
  ledgerKeyOf,
} from "./load/extension.js";
export {
  END_STATE_ROOT,
  endStateObjectiveId,
  lowerCampaigns,
  lowerEndState,
} from "./manifest/lower.js";
export {
  type CampaignProbeSpec,
  type CampaignProbesSpec,
  CampaignsManifest,
  type CampaignSpec,
  DEFAULT_LEDGER_DIR,
  type DetectorSpec,
  durationMs,
  type EndStateSpec,
  type ObjectiveSpec,
  type PerimeterSpec,
  type PhaseSpec,
  type SectorTermSpec,
  type SyntaxTermSpec,
} from "./manifest/spec.js";
export {
  type CampaignPredicate,
  type CampaignPredicateInput,
  type CampaignSubject,
  type Range,
} from "./ports/campaign-predicate.js";
export {
  NO_REPORTS,
  type ReportSource,
  reportSourcesOf,
  type ReportSpec,
} from "./ports/report-source.js";
